### ISSUE TITLE
R2, R3, R4 and R7

### ISSUE THREAD

**Issue by Alexgtc** [skot/bitaxeGamma#4]
Does anyone know why the list of materials does not show the resistances r2, r3, r4 and r7 and in the gerbers yes? Can the plate be mounted leaving those resistors unmounted?

**Comment by marplukiwi** [comment]
According to the circuit diagram, the resistors are not needed
<img width="580" alt="Bildschirmfoto 2024-09-19 um 09 18 41" src="https://github.com/user-attachments/assets/86a11758-915c-4bb5-84e3-75351352876c">

**Comment by Alexgtc** [comment]
Ok, so leaving those resistors without mounting, the gamma bitaxe should work without problems, right?

**Comment by marplukiwi** [comment]
If the documentation, i.e. the circuit diagram, is correct then yes. But I cannot confirm this.

**Comment by Alexgtc** [comment]
Ok, I'll try to mount it without those resistances to see if it works. Thank you for the help.

**Comment by yellowpi** [comment]
@skot dear skot, what do you say about this?

**Comment by skot** [comment]
@marplukiwi is correct, R2, R3, R4 and R7 are DNP meaning "Do Not Place".

**Comment by marplukiwi** [comment]
@skot and R18 DNP or not? R18 is in the BOM but crossed out in the circuit diagram.

**Comment by skot** [comment]
The red X in KiCad means DNP
